### ISSUE TITLE
`test_remove_with_resources_present` fails

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/seldon-core-operator#145]
`test_remove_with_resources_present` fails on the HEAD of main

so far the issue is narrowed down that only one CRD of possible 3 is possible in order not to fail. 
That means that only one of those tests is allowed before `test_remove_with_resources_present`:

- test_seldon_predictor_server[sklearn.yaml]
- test_seldon_predictor_server[sklearn2.yaml]
- test_seldon_deployment

if at least 2 from above list are present, then test `test_remove_with_resources_present` fails

**Comment by beliaev-maksim** [comment]
might be related to https://github.com/juju/python-libjuju/issues/877

**Comment by i-chvets** [comment]
Tested without `test_remove_with_resources_present`, but with all tests present. All tests pass, **BUT** same error is seen:
```
Task exception was never retrieved
future: <Task finished name='Task-614' coro=<Connection._connect.<locals>._try_endpoint() done, defined at /home/ichvets/cw/dev/seldon-core-operator/.tox/integration/lib/python3.8/site-packages/juju/client/connection.py:758> exception=OSError(9, 'Bad file descriptor')>
Traceback (most recent call last):
```

**Comment by i-chvets** [comment]
Even if I skip ALL tests, only do deploy and remove, removal test hangs.
Application is actually removed, but it still stays in `ops_test.model.applications`

**Comment by i-chvets** [comment]
**Analysis**
Failure to properly update `ops_test.model.application` during the remove test is most likely due to the race condition that is created by deployment and deletion of multiple SeldonDeployments in other tests.

When remove tests is executed, charm goes into 'terminated' state:
```
$ juju status
Model            Controller          Cloud/Region        Version  SLA          Timestamp
test-charm-ko7i  microk8s-localhost  microk8s/localhost  2.9.42   unsupported  16:19:43-04:00

App                        Version  Status      Scale  Charm        Channel  Rev  Address         Exposed  Message
seldon-controller-manager           terminated    0/1  seldon-core             0  10.152.183.177  no       unit stopped by the cloud

Unit                          Workload    Agent  Address     Ports  Message
seldon-controller-manager/0*  terminated  lost   10.1.59.75         unit stopped by the cloud
```

However, `jhack tail` does not show `stop` or `remove` events:
```
$ jhack tail
                                             ┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                             
                                             ┃ timestamp ┃ seldon-controller-manager/0 ┃                                             
                                             ┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩                                             
                                             │ 16:13:55  │ start                       │                                             
                                             │ 16:13:54  │ config_changed              │                                             
                                             │ 16:13:52  │ seldon_core_pebble_ready    │                                             
                                             │ 16:13:48  │ leader_elected              │                                             
                                             │ 16:13:47  │ install                     │                                             
                                             └───────────┴─────────────────────────────┘  
```

**Suggestions/experimentation**
Add idle `wait_for_idle` calls to deployment tests to allow workload container to settle when deleting SeldonDeployments.
Add `stop` event handler that stops workload container.
