### ISSUE TITLE
Seldon-istio relation does not work with charmed istio

### ISSUE THREAD

**Issue by Barteus** [canonical/seldon-core-operator#18]
We need Istio to provide external access to models and canary deployments.

Right now relating the istio-pilot with seldon-controller-manager is not possible. The default values are also not working for CKF, they require default Istio installation in `istio-system` namespace

**Comment by Barteus** [comment]
Example for testing can be found here: https://docs.seldon.io/projects/seldon-core/en/latest/examples/istio_canary.html

**Comment by ca-scribner** [comment]
@Barteus #20 should fix this issue.  It works for me locally and I've been able to deploy canaries, etc.  Only thing left is adding a bit more to the new demo notebook (`examples/ingress_canary_and_auth.ipynb`) for the case with authentication through dex.  Let me know how it works out for you - that demo notebook is a good place to start for testing/seeing how things work.

**Comment by ca-scribner** [comment]
Sorry I should have clarified in my last msg that the example in #20 is written using the `latest/stable` istio/dex, but those charms are still being debugged so if you try to use it for now you should use the same istio/dex that are in the bundle rather than just deploying from latest/stable.  Once they get updated (next week or two?) the example will work as is

**Comment by ca-scribner** [comment]
`examples/ingress_canary_and_auth.ipynb` in #20 now has authenticated examples as well

**Comment by misohu** [comment]
[Jira issue](https://warthogs.atlassian.net/browse/KF-214?atlOrigin=eyJpIjoiNWIyNjA3Zjk2YjQyNGExZmE3N2ZjYmJlYzI4OGIxYjQiLCJwIjoiaiJ9)

**Comment by i-chvets** [comment]
PR is merged. See testing procedures in corresponding PR https://github.com/canonical/seldon-core-operator/pull/48
Closing this issue.
