### ISSUE TITLE
seldon-core 1.15 is not compatible with k8s 1.25

### ISSUE THREAD

**Issue by NohaIhab** [canonical/seldon-core-operator#211]
### Bug Description

According to the [seldon docs](https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html#kubernetes-compatibility-matrix), seldon version 1.15 is not compatible with k8s 1.25.
PR #207 bumps microk8s in the CI to 1.25, it's failing as expected with seldon 1.15.

Seldon will be updated to 1.17 as part of the 1.8 release, as documented in https://github.com/canonical/bundle-kubeflow/issues/643. Seldon 1.17 is compatible with k8s 1.25, so we should update the k8s version in the CI along with the manifests and version update.

**Comment by DnPlas** [comment]
https://github.com/canonical/seldon-core-operator/pull/216 updated the version of Seldon in the `main` and `track/1.17` branches, which means that this issue should not happen anymore in the CIs of those. Closing this issue as it is not relevant anymore.
