### ISSUE TITLE
Seldon Core only deploys correctly with 'seldon-controller-manager' application name

### ISSUE THREAD

**Issue by DomFleischmann** [canonical/seldon-core-operator#5]
When deploying the seldon-core operator with its default application name `seldon-core` the container gets into an error state. This also happens if it is given any other application-name besides `seldon-controller-manager`.

Steps to reproduce:
`juju deploy seldon-core`

**Comment by knkski** [comment]
It's hardcoded upstream:

https://github.com/SeldonIO/seldon-core/blob/master/operator/constants/constants.go#L44

**Comment by DomFleischmann** [comment]
Upstream bug filed [here](https://github.com/SeldonIO/seldon-core/issues/3733).

**Comment by ca-scribner** [comment]
Until upstream fixes this bug, we should add a check in our charm that Blocks the charm with a clear error message telling the user to deploy with the charm renamed

**Comment by DnPlas** [comment]
Upstream has closed the mentioned issue, the hardcoded value is changed in v2, though we are still using seldon v1. Until we move to this newer version, we'll have to deploy seldon as `seldon-controller-manager`.
