### ISSUE TITLE
`_gen_certs` using incorrect `ApiError`?

### ISSUE THREAD

**Issue by ca-scribner** [canonical/seldon-core-operator#77]
I think [this use of ApiError](https://github.com/canonical/seldon-core-operator/blob/f7fad60a435d1687e7a84d7059a1c23311297960/src/charm.py#L338) might be a bug.  The ApiError caught here is a lightkube ApiError, but we're catching errors that are thrown from file operation calls.

**Comment by i-chvets** [comment]
Fix is merged.
