### ISSUE TITLE
Re-design Install event handler

### ISSUE THREAD

**Issue by i-chvets** [canonical/seldon-core-operator#85]
Install event handler needs to be redesigned to deploy K8S resources and update Pebble layer. All other actions should be performed in Pebble Ready event handler and in `main`.

**Comment by i-chvets** [comment]
# Re-design Install event handler
Work items are tracked in https://warthogs.atlassian.net/browse/KF-842
Branch: https://github.com/canonical/seldon-core-operator/tree/kf-842-gh85-fix-redesign-install-event-handler

When Install event is fired container might not be ready and many actions that are taken will not be performed. Handling of Install event and Pebble Ready event should be reviewed and redesigned to ensure correct deployment.

## Design
Install event handler performs same actions as Pebble Ready event handler.
Pebble Ready event handler has container connection check that ensures that all actions are performed only when container is available.
Container connection check indicates Maintenance status if container is not ready.

## Testing
Integration testing.

**Comment by i-chvets** [comment]
Fix is merged.

**Comment by DnPlas** [comment]
Fixed by #86
